using System;
using System.Text;
using System.Linq;

namespace S05_Password;

public class Password
{
	// The benefits of using const instead of readonly in this case are: performance and memory efficiency, compile-time checking, and thread safety
	private const string _base = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ123456789£$%&?@#";

	// The main advantage of using static for these methods in this case is that it allows them to be called without creating an instance of the Password class. This can provide the following benefits: performance improvement, memory efficiency, code clarity and organization, utility/helper method
	public static string GeneraConArray(int length) {
		char[] pw = new char[length];
		Random rand = new();

		for (int i = 0; i < length; i++) {
			pw[i] = Password._base[rand.Next(Password._base.Length)];
		}
		return new string(pw);
	}

	public static string GeneraConBuilder(int length)
	{
		StringBuilder pw = new(length);
		Random rand = new();

		for (int i = 0; i < length; i++)
		{
			pw.Append(Password._base[rand.Next(Password._base.Length)]);
		}
		return pw.ToString();
	}

	public static string GeneraConSubstring(int length)
	{
		char[] pw = new char[length];
		Random rand = new();

		for (int i = 0; i < length; i++)
		{
			// Con questi due passaggi, viene estratta una sottostringa casuale di lunghezza 1
			int start = rand.Next(Password._base.Length - (length - i));
			string randomSubstring = Password._base.Substring(start, 1);
			pw[i] = randomSubstring[0];
		}
		return new string(pw);
	}

	public static string GeneraConShuffle(int length)
	{
		char[] baseChars = Password._base.ToCharArray();
		Random rand = new();

		// This lambda expression takes a single parameter x (representing an element in the array), and returns a new random integer value generated by rand.Next(). This random value is then used as the key for sorting the elements, effectively shuffling the array.
		baseChars = baseChars.OrderBy(x => rand.Next()).ToArray();

		// Take(length) is used to take the first length characters from the shuffled array
		return new string(baseChars.Take(length).ToArray());
	}
}
